### ISSUE TITLE
 the effect on the Scaled dataset 

### ISSUE THREAD

**Issue by wwj-53** [CUHK-AIM-Group/EndoGaussian#22]
Hello, I used keyfream1 from the scaled dataset to run the code. The dataset has been processed as required. I ran as follows:
python train.py -s /media/wwj/3dGSDATA/dataset_3/keyframe_1 --port 6017 --expname dataset_3/keyframe_1 --configs arguments/scared/d3k1.py 。
Then Python render. py -- model_path output/dataset_1/keyframe_1-- skip_train -- skip_video -- configs arguments/scaled/d3k1. py

The results obtained are as follows：
Metric evaluation progress: 100%| 11/11 [00:00<00:00, 12.03it/s]
Scene:  output/try_scared SSIM :    0.6458519
Scene:  output/try_scared PSNR :   20.9398842
Scene:  output/try_scared LPIPS:    0.4690880
Scene:  output/try_scared RMSE:   51.9106958

The rendered image is shown below：
![00000](https://github.com/yifliu3/EndoGaussian/assets/84660519/a1706492-cff5-4452-922d-c6171dd32a76)

May I ask how I can adjust to achieve the effect close to the paper? (I used the parameters of your code and the Endonerf dataset to achieve the effect close to the paper, but the effect on the Scaled dataset is very poor)?

**Comment by yifliu3** [comment]
Hi, thanks for your attention.

We haven't found similar problems before, and I think something unusual happens. To find the problem, can you provide more information, like:
1. Can other subdatasets normally trained and rendered?
2. Have you pre-processed the dataset following README?

**Comment by Rashfu** [comment]
Hi, @yifliu3. I follow the README to process the scared dataset, but I got the similar results as mentioned in this issue.  I guess there is something wrong with d3k1....

Here are the results of different subset:
'''
Scene:  output/scared/d1k1 SSIM :    0.8441468
Scene:  output/scared/d1k1 PSNR :   28.5188026
Scene:  output/scared/d1k1 PSNR* :   26.8898849
Scene:  output/scared/d1k1 LPIPS:    0.1462189
Scene:  output/scared/d1k1 FLIP:    0.0969261
Scene:  output/scared/d1k1 RMSE:    2.2612323


Scene:  output/scared/d2k1 SSIM :    0.8499609
Scene:  output/scared/d2k1 PSNR :   28.1629581
Scene:  output/scared/d2k1 PSNR* :   25.3476257
Scene:  output/scared/d2k1 LPIPS:    0.1233200
Scene:  output/scared/d2k1 FLIP:    0.1104282
Scene:  output/scared/d2k1 RMSE:    1.3590266

Scene:  output/scared/d3k1 SSIM :    0.6335039
Scene:  output/scared/d3k1 PSNR :   19.9522858
Scene:  output/scared/d3k1 PSNR* :   19.0710773
Scene:  output/scared/d3k1 LPIPS:    0.4875128
Scene:  output/scared/d3k1 FLIP:    0.2678323
Scene:  output/scared/d3k1 RMSE:    6.1003008

Scene:  output/scared/d6k1 SSIM :    0.8906089
Scene:  output/scared/d6k1 PSNR :   28.4541473
Scene:  output/scared/d6k1 PSNR* :   27.9744625
Scene:  output/scared/d6k1 LPIPS:    0.3716555
Scene:  output/scared/d6k1 FLIP:    0.1171003
Scene:  output/scared/d6k1 RMSE:    2.0374999

Scene:  output/scared/d7k1 SSIM :    0.8688353
Scene:  output/scared/d7k1 PSNR :   26.4645214
Scene:  output/scared/d7k1 PSNR* :   24.4782009
Scene:  output/scared/d7k1 LPIPS:    0.2273238
Scene:  output/scared/d7k1 FLIP:    0.1385011
Scene:  output/scared/d7k1 RMSE:    3.4184709
'''
