### ISSUE TITLE
Reconstructed 3DGS visualization

### ISSUE THREAD

**Issue by Loping151** [CUHK-AIM-Group/EndoGaussian#24]
I understand that you provide reconstructed point cloud as visualization as in 
https://github.com/CUHK-AIM-Group/EndoGaussian/issues/4. Now I want to extract a static GS model at a certain timestamp. This is what I got.

![image](https://github.com/user-attachments/assets/260934eb-5c1b-41ec-b1fd-484b0eabf661)
![image](https://github.com/user-attachments/assets/ddff1804-1b98-476c-8748-d96c7fa68b22)
(I filtered gaussians with large scales in advance so there is blank in mask area)

This GS model can be splatted into correct RGB and depth. I just wonder if the GS you got is also like this.

*I fully appreciate your work and your kind open source.

**Comment by yifliu3** [comment]
Thanks for your attention.  Yes the visualization of Gaussians is similar to my own observation.

**Comment by Loping151** [comment]
Thank you for your instant reply
