### ISSUE TITLE
Unstable training results and PSNR is only 5.

### ISSUE THREAD

**Issue by Beilinlin** [CUHK-AIM-Group/EndoGaussian#25]
Dear Author,

I have encountered the same issue as the previous questioner during the training process. In the coarse stage, the training is unstable. Without changing any code or commands, the PSNR values in two coarse stage runs were 25.65 and 5.65 respectively (most of the time, the values are around 5)
![图片1](https://github.com/user-attachments/assets/de6a0139-f476-4124-b07f-b2bc097a65d6)
![图片2](https://github.com/user-attachments/assets/d674fe69-d03a-42c0-8f5a-53d9e43b5b89)

Additionally, in the fine stage, the PSNR value consistently hovers around 5, and the loss value remains around 0.49.
My setup includes an NVIDIA GeForce RTX 4090 GPU with 24564MiB of memory. My CUDA version is 11.7, and my Python version is 3.7.16.

Have you encountered these issues during training? How can they be resolved?

I apologize for the disturbance and greatly appreciate your help!Thank you very much!

**Comment by yifliu3** [comment]
Dear Beilinlin,

Thanks for your attention. I just realized that your problem is very similar to the one raised at #11 . Maybe you can check that first.

**Comment by Beilinlin** [comment]
Thank you very much! After manually downloading the submodules again, the issue has been resolved!
