### ISSUE TITLE
HexPlane or K-Plane

### ISSUE THREAD

**Issue by haowang020110** [CUHK-AIM-Group/EndoGaussian#29]
Hi, there
It seemed that the 4D voxel used in EndoGaussian is K-plane which is also used in 4DGS-HUST
https://github.com/CUHK-AIM-Group/EndoGaussian/blob/47c23a953fa211835a3d4113f0075e7815bebeca/scene/hexplane.py#L95-L96
Not the Hexplane mentioned in EndoGaussian paper. I am not sure, may be something wrong with my understanding about difference between Hexplane and K-plane.

**Comment by yifliu3** [comment]
Hi, I've checked the reference. The 4D voxel used in EndoGaussian is from K-plane, but the 4D version of K-plane is also named Hex-plane. We will fix this reference in the future version.

**Comment by haowang020110** [comment]
Hi, thanks a lot for your reply!
