### ISSUE TITLE
There is a spelling error in the render.py file

### ISSUE THREAD

**Issue by teym822** [CUHK-AIM-Group/EndoGaussian#31]
![微信图片_20241002181359](https://github.com/user-attachments/assets/30e71411-d58c-4120-a0ee-091c31f30257)

On line 129, there is a mistake in "reconstruct".This causes me to make errors when rendering images if I skip training，you can make modifications to this to prevent others from making similar mistakes.

**Comment by yifliu3** [comment]
Thanks for your help! We will fix it later.
