### ISSUE TITLE
Question Regarding FPS Measurement Method for EndoGaussian-Binocular Results on EndoNeRF and SCARED Datasets

### ISSUE THREAD

**Issue by sandokim** [CUHK-AIM-Group/EndoGaussian#35]
Hello,

I'm working with the EndoNeRF and SCARED datasets and noticed that the FPS values reported in your paper (195.09 FPS for EndoNeRF and 181.20 FPS for SCARED) are much higher than what I observed.

For EndoNeRF (cutting and pulling), I ran:

- EndoNeRF (cutting):
```css
python render.py -m output/endonerf/cutting_tissues_twice --skip_train --skip_video --configs arguments/endonerf/cutting.py
```
FPS = 12.0 (156 frames in 13 seconds observed with tqdm during `Render 2D images`)

- EndoNeRF (pulling):
```css
python render.py -m output/endonerf/pulling_soft_tissues --skip_train --skip_video --configs arguments/endonerf/pulling.py
```
FPS = 12.6 (63 frames in 5 seconds observed with tqdm during `Render 2D images`)

For SCARED, FPS cannot be calculated because the rendering finishes too quickly (e.g., 13 frames in 0 seconds).

I was wondering if there is a specific code or setup used to calculate the FPS values for EndoNeRF and SCARED datasets in your paper. If I misunderstood something, I would really appreciate it if you could clarify.

Thank you.

**Comment by yifliu3** [comment]
Thanks for your interest. The reported time seems unusual, please check:

- No one is sharing or competing for the same GPU with you while using it.
- CPU is normally running
- should measure the rendering time immediately before and after the render operation using the time() function to avoid including data loading and metric calculation times.

**Comment by sandokim** [comment]
I figured there's an option `render_test` in the `render.py` file that can be used to check FPS.

On the NVIDIA RTX 6000 Ada, the FPS results are as follows:

- ENDONERF dataset (pulling, cutting): Average FPS = 189.95
- SCARED dataset (d1k1, d2k1, d3k1, d6k1, d7k1): Average FPS = 214.96

Thank you for clarify this.

**Comment by yifliu3** [comment]
Glad to hear the issue has been resolved! I will temporarily close this issue. If you have any further questions, please don’t hesitate to reach out. Best regards.
